import { makeStyles } from "@material-ui/core/styles";
const useStyles = makeStyles((theme) => ({
    root: {
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        marginTop: "5rem",
        minWidth: "15rem",
        padding: "2px",
    },
    title: {
        marginTop: "3rem",
        marginBottom: "2rem",
    },
    titleText: {
        width: "4rem",
    },
    habitContainer: {
        alignItems: "center",
        minWidth: "10rem",
        maxWidth: "30rem",
        minHeight: "14rem",
        margin: "auto",
        backgroundColor: "#303038",
        borderRadius: "10px",
        padding: "0.5rem",
    },
    textGrey: {
        color: "#6c6c72",
    },
    textWhite: {
        color: "#ffffff",
        fontWeight: "bold",
    },
    habitTitleBox: {
        width: "100%",
        color: "white",
    },
    grey: {
        color: "#ffffff",
        border: "2px solid",
        borderRadius: "2rem",
        backgroundColor: "#6c6c72",
        borderColor: "#6c6c72",
    },
    white: {
        backgroundColor: "#ffffff",
    },
    black: {
        color: "#ffffff",
        border: "2px solid",
        borderRadius: "2rem",
        backgroundColor: "#000000",
        borderColor: "#000000",
    },
    yellow: {
        color: "#ffffff",
        border: "2px solid",
        borderRadius: "2rem",
        backgroundColor: "#FFB427",
        borderColor: "#FFB427",
    },
    selectedDate: {},
    unSelectedDate: {},
    blue: {
        color: "#ffffff",
        border: "2px solid",
        borderRadius: "2rem",
        backgroundColor: "#5666F3",
        borderColor: "#5666F3",
    },
    green: {
        color: "#ffffff",
        border: "2px solid",
        borderRadius: "2rem",
        backgroundColor: "#50D890",
        borderColor: "#50D890",
    },
    pink: {
        color: "#ffffff",
        border: "2px solid",
        borderRadius: "2rem",
        borderColor: "#D96383",
        backgroundColor: "#D96383",
    },
    backgroundYellow: {
        backgroundColor: "#FFB427",
        borderColor: "#FFB427",
    },
    datesBox: {
        marginTop: "10px",
        height: "2rem",
        width: "2rem",
        textAlign: "center",
        lineHeight: "2rem",
    },
    selected: {
        marginTop: "0.5rem",
        marginLeft: "auto",
        marginRight: "auto",
        height: "2rem",
        width: "2rem",
        textAlign: "center",
        lineHeight: "2rem",
        color: "#ffffff",
        border: "2px solid",
        borderRadius: "2rem",
        textShadow: "0.5px 0.5px 1px #000000eb",
        cursor: "pointer",
        boxShadow: "1px 1px 4px 0px #000000ab",
    },
    unSelected: {
        marginTop: "0.5rem",
        marginLeft: "auto",
        marginRight: "auto",
        height: "2rem",
        width: "2rem",
        textAlign: "center",
        lineHeight: "2rem",
        border: "2px solid",
        borderRadius: "2rem",
        cursor: "pointer",
    },
}));

export default useStyles;
